[window]
padding = {x=10, y=10}

[font]
normal = {family="jetbrains mono", style="Regular"}
size = 8

[colors.primary]
foreground = "#eadbb2"
background = "#282828"

[colors.normal]
black = "#2b2b2b"
white = "#eadbb2"
red = "#cc231c"
green = "#689d69"
yellow = "#d79922"
blue = "#458587"
cyan = "#458587"
magenta = "#874566"

[colors.bright]
black = "#2b2b2b"
white = "#eadbb2"
red = "#cc231c"
green = "#689d69"
yellow = "#d79922"
blue = "#458587"
cyan = "#458587"
magenta = "#874566"
